# # .readthedocs.yml

# version: 2

# build:
#   os: ubuntu-22.04
#   tools:
#     python: "3.11"

# sphinx:
#   configuration: docs/source/conf.py

# python:
#   install:
#     - requirements: docs/requirements.txt
#     - method: pip
#       path: .
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-latest   # 或 mambaforge-23.11 等受支持的标签

conda:
  environment: environment.yml

sphinx:
  configuration: docs/source/conf.py
